name: Build and Push Docker Images

on:
  push:
    branches: [ main, abid_test1 ]  # Updated to include your test branch
  pull_request:
    branches: [ main, abid_test1 ]
 
env:
  DOCKER_HUB_USERNAME: abidhasan83  # Your Docker Hub username

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Extract metadata for backend
      id: meta-backend
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_HUB_USERNAME }}/agrolink-backend
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix=sha-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Extract metadata for mobile
      id: meta-mobile
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_HUB_USERNAME }}/agrolink-mobile
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix=sha-
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ steps.meta-backend.outputs.tags }}
        labels: ${{ steps.meta-backend.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          MONGO_URI=${{ secrets.MONGO_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
          NODE_ENV=production
        
    - name: Build and push mobile image
      uses: docker/build-push-action@v5
      with:
        context: ./mobile
        file: ./mobile/Dockerfile
        push: true
        tags: ${{ steps.meta-mobile.outputs.tags }}
        labels: ${{ steps.meta-mobile.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Print image information
      run: |
        echo "Backend images pushed:"
        echo "${{ steps.meta-backend.outputs.tags }}"
        echo "Mobile images pushed:"
        echo "${{ steps.meta-mobile.outputs.tags }}"
